Optical flow loader for Davis dataset
fvisin/dataset_loaders pull request #10
Opened 2017-06-03 11:07 UTC by fral92

2017-06-03 14:38 UTC, fvisin requested changes
Thank you for the PR. Looks good overall, but I was wondering if you can make it more general so that we can share it with the other datasets.

How hard do you think it could be to move the relevant code in parallel_loader.py, where the data augmentation takes place? I don't have time to look into it in detail now, but I think it should be easy to check whether there is a dir in the dataset path containing the requested optical flow and in that case to load it from there rather than computing it.

From a high level perspective, this is what I would check:
- the optical flow should be computed on the unprocessed (uncropped / skewed / etc ..) image, so that we don't have to store all the possible transformations. I am afraid that we are doing the opposite at the moment (not to have to transform the OF), it should be checked what would be the downsides to do it the other way around
- define a standard way to name the directory and the images. The dir should be named after the technique and the chosen parameters.
- provide a flag to store the processed frames automatically (i.e., the first time we compute the OF and there is no local cache, if the flag is True we store the OF frames)

Do you think you have time to look into it and make these changes?

2017-06-03 14:38 UTC, fvisin commented on dataset_loaders/videos/davis.py
> +            if optical_flow_type not in ['Brox', 'Farn', 'LK', 'TVL1']:
Add `None` to the list and merge the two conditions.

2017-06-03 14:38 UTC, fvisin commented on dataset_loaders/videos/davis.py
>                   *args, **kwargs):
Please add a description of the parameters (some of them you can copy from other datasets)

2017-06-07 10:48 UTC, marcociccone commented
I'm going to close this because of #12

2017-06-07 13:35 UTC, closed without merging