Update __init__.py
fvisin/dataset_loaders pull request #6
Opened 2017-05-31 17:13 UTC by lamblin

- use __all__ to avoid #noqa
- make sure we call "git rev-parse HEAD" in the right directory

2017-06-03 16:17 UTC, fvisin requested changes

2017-06-03 16:17 UTC, fvisin commented on dataset_loaders/__init__.py
> +from unidimensional.cortical_layers import Cortical6LayersDataset
Can you please remove this, so that I can merge it before we merge the other PR?

2017-06-03 16:17 UTC, fvisin commented on dataset_loaders/__init__.py
> +    "Cortical6LayersDataset",
And here as well.

2017-06-20 18:00 UTC, lamblin commented on dataset_loaders/__init__.py
> +from unidimensional.cortical_layers import Cortical6LayersDataset
Of course, I thought I had removed it, but obviously I forgot.

2017-06-20 18:05 UTC, lamblin commented on dataset_loaders/__init__.py
> +from unidimensional.cortical_layers import Cortical6LayersDataset
Here you go. They were unstaged changes in my repo...

2017-06-22 09:09 UTC, merged

2017-06-22 09:09 UTC, fvisin commented
Merged. Thanks for the PR!